/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) {
        int x = 1;
        int y = 2;
        System.out.println(x);
        System.out.println(y);

    }
}
